# Use an official Python runtime as a parent image
FROM python:2.7-slim
# Set the working directory to /app
WORKDIR /app
Sensitivity: Internal & Restricted
# Copy the current directory contents into the container at /app
ADD . /app
# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt
# Make port 80 available to the world outside this container
EXPOSE 80
# Define environment variable
ENV NAME World
# Run app.py when the container launches
CMD ["python", "app.py"]






#mysql -u root -p
devops

#show database; (To check what are database are avilable)

#create database Nov18_db; (Database name)

#use Nov18_db; (To our connect db)

#show tables; (List all table in that database)

#CREATE TABLE `customer_information` (
	`cust_id` INT(11) NOT NULL AUTO_INCREMENT,
	`cust_name` VARCHAR(150) NULL DEFAULT NULL,
	`cust_email` VARCHAR(150) NULL DEFAULT NULL,
	`cust_pwd` VARCHAR(150) NULL DEFAULT NULL,
	`cust_staysignedin` VARCHAR(150) NULL DEFAULT NULL,
	`cust_gender` VARCHAR(150) NULL DEFAULT NULL,
	`cust_mobilenumber` VARCHAR(150) NULL DEFAULT NULL,
	PRIMARY KEY (`cust_id`)
);

#select * from customer_information;
